name: Test Casedoxx LoadFile Creator

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_streamlit.txt
        pip install -r requirements_review.txt
        pip install pytest pytest-cov
    
    - name: Create test directories
      run: |
        mkdir -p uploads
        mkdir -p outputs
        mkdir -p review_data
        mkdir -p test_samples
    
    - name: Run basic tests
      run: |
        python -c "import sys; print('Python version:', sys.version)"
        python -c "import streamlit; print('Streamlit version:', streamlit.__version__)"
        python -c "import pandas; print('Pandas version:', pandas.__version__)"
    
    - name: Test review workflow
      run: |
        python test_review_workflow.py
      continue-on-error: true
    
    - name: Test configuration
      run: |
        python -c "from config_manager import ConfigManager; cm = ConfigManager(); print('Config loaded successfully')"
    
    - name: Run pytest
      run: |
        pytest tests/ -v --cov=. --cov-report=xml
      continue-on-error: true
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false 